apiVersion: apps/v1
kind: Deployment
metadata:
  name: minimum-pod-scheduler
  labels:
    app: minimum-pod-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minimum-pod-scheduler
  template:
    metadata:
      labels:
        app: minimum-pod-scheduler
    spec:
      serviceAccount: minimum-pod-scheduler
      containers:
        - name: minimum-pod-scheduler
          image: dgrlabs/minimum-pod-scheduler:v0.2
          imagePullPolicy: Always
